artists/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('resume/', include('resume.urls')),
    path('admin/', admin.site.urls),
]

resume/urls.py
from django.urls import path

# app imports
from . import views


app_name = 'resume'
urlpatterns = [
    path('', views.IndexView.as_view(), name='artists'),
    path('artist/<uuid:artist_id>/', views.DetailView.as_view(), name='artist_detail'),
    path('artist/create/', views.ArtistCreate.as_view(), name='artist_create'),
]

resume/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


LANGUAGES = [
    ('en', _(u'English')),
    ('fr', _(u'French')),
    ('ga', _(u'Irish')),
    ('de', _(u'German')),
    ('it', _(u'Italian')),
    ('pl', _(u'Polish')),
    ('pt', _(u'Portuguese')),
]


class Artist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    stage_name = models.CharField(max_length=100, blank=True)  # (optional)
    email = models.EmailField(max_length=254, blank=False, unique=True)  # (uniqueness)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    telephone_number = models.CharField(max_length=11, blank=True)  # (optional)
    biography = models.TextField(blank=True)  # (optional)

    def get_absolute_url(self):
        return reverse('resume:artist_detail', kwargs={'artist_id': self.id})

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'


class Language(models.Model):
    artist = models.ManyToManyField('Artist', related_name='language', blank=True, null=True)
    name = models.CharField(max_length=7, choices=LANGUAGES)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=100)
    artist = models.ForeignKey('Artist', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

resume/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.views.generic.edit import CreateView

# app imports
from .models import Artist


class IndexView(generic.ListView):
    template_name = 'resume/artists.html'
    context_object_name = 'artist_list'

    def get_queryset(self):
        return Artist.objects.order_by('-date_created')[:3]


class ArtistCreate(CreateView):
    model = Artist
    fields = ['first_name', 'last_name', 'email']


class DetailView(generic.DetailView):
    model = Artist
    template_name = 'resume/artist_detail.html'

    def get_object(self, queryset=None):
        return Artist.objects.get(id=self.kwargs.get('artist_id'))

resume/templates/includes/navbar.html
{% block resume_navigation %}
  <nav class="resume-navigation">
    <ul>
      <li><a href="{% url 'resume:artist_create' %}">Add artist</a></li>
    </ul>
  </nav>
{% endblock resume_navigation %}

resume/templates/resume/artist_detail.html
<h3>Menu</h3>
<ul>
  <li><a href="{% url 'resume:artists' %}">Home</a></li>
</ul>

<h2>{{ artist.first_name }} {{ artist.last_name }}</h2>

<ul>
  <li>Stage name: {{ artist.stage_name }}</li>
  <li>Email: {{ artist.email }}</li>

  {% if artist.telephone_number %}
    <li>Telephone number: {{ artist.telephone_number }}</li>
  {% endif %}

  {% if artist.biography %}
    <li>Biography: {{ artist.biography }}</li>
  {% endif %}
</ul>

resume/templates/resume/artist_form.html
<form action="" method="POST">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>

resume/templates/resume/artists.html
{% extends "base.html" %}

{% block main %}
  <!-- navigation -->
  {% include "includes/navbar.html" %}

  {% if artist_list %}
    <h3>Artists</h3>
    <ul>
    {% for artist in artist_list %}
    <li><a href="{% url 'resume:artist_detail' artist.id %}">{{ artist }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No artists available</p>
    {% endif %}
{% endblock main %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Supporting Artists</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
  <div id="main">
    <h1>Supporting Artists</h1>
    {% block main %}
    {% endblock main %}
  </div>
  <footer class="footer">
    <div id="credits">
      <p>Made by Pedro Curado
        <a class="icon-brands linkedin"
           href="https://www.linkedin.com/in/pedrocurado/"
           target="_blank"></a>
        <a class="icon-brands github"
           href="https://github.com/p3dr0migue1"
           target="_blank"></a>
      </p>
    </div>
  </footer>
</body>
</html>